// <auto-generated />
using CompreSuaFruta.Dal.Context.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompreSuaFruta.Dal.Migrations.StatusVendaDb
{
    [DbContext(typeof(StatusVendaDbContext))]
    [Migration("20210305193544_migrations")]
    partial class migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("CompreSuaFruta.Dal.Context.Entities.StatusVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("StatusVendas");
                });
#pragma warning restore 612, 618
        }
    }
}
