// <auto-generated />
using CompreSuaFruta.Dal.Context.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompreSuaFruta.Dal.Migrations
{
    [DbContext(typeof(ProdutoVendaDbContext))]
    [Migration("20210306181608_Migrations")]
    partial class Migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("CompreSuaFruta.Model.Models.ProdutoVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdProduto");

                    b.Property<int>("QuantidadeProduto");

                    b.Property<double>("ValorTotal");

                    b.Property<double>("ValorUnitario");

                    b.HasKey("Id");

                    b.ToTable("ProdutoVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
